site_name: JAX-AMG
site_description: JAX bindings for NVIDIA AmgX sparse linear solver

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_symbol_type_heading: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Installation: install.md
  - Examples: examples.md
  - Solver Configuration: config.md
  - MPI: mpi.md
  - Caching: caching.md
  - Environment Variables: environ.md
  - API Reference: api.md
