from typing import Any

mpi_enabled: bool

def get_amgx_solve_handler() -> Any: ...
def get_amgx_solve_double_handler() -> Any: ...
def get_amgx_solve_mpi_handler() -> Any: ...
def get_amgx_solve_mpi_double_handler() -> Any: ...
def initialize() -> None: ...
def finalize() -> None: ...
def clear_solver_cache() -> None: ...
def get_solver_cache_info() -> dict[str, Any]: ...
def get_stats_string() -> str: ...

# Rank-local arrays (see jaxamg.local_arrays).
def get_local_array_handler() -> Any: ...
def register_local_array(array_id: int, data_pointer: int, nbytes: int) -> None: ...
def release_local_array(array_id: int) -> None: ...
def local_array_count() -> int: ...
def synchronize_devices(devices: list[int]) -> None: ...

# Neighbour exchange plans (MPI builds only; see jaxamg.transport).
def get_neighbour_exchange_handler() -> Any: ...
def register_exchange_plan(
    plan_id: int,
    comm_handle: int,
    send_peers: list[int],
    send_counts: list[int],
    recv_peers: list[int],
    recv_counts: list[int],
) -> None: ...
def release_exchange_plan(plan_id: int) -> None: ...
def exchange_plan_count() -> int: ...
