from typing import Any

def get_amgx_solve_handler() -> Any: ...
def get_amgx_solve_double_handler() -> Any: ...
def get_amgx_solve_mpi_handler() -> Any: ...
def get_amgx_solve_mpi_double_handler() -> Any: ...
def initialize() -> None: ...
def finalize() -> None: ...
def clear_solver_cache() -> None: ...
def get_solver_cache_info() -> dict[str, Any]: ...
