from typing import Any

def get_amgx_solve_handler() -> Any: ...
def get_amgx_solve_double_handler() -> Any: ...
def get_amgx_solve_mpi_handler() -> Any: ...
def get_amgx_solve_mpi_double_handler() -> Any: ...
def get_amgx_allgather_handler() -> Any: ...
def get_amgx_allgather_double_handler() -> Any: ...
def finalize() -> None: ...
